# Generated by Django 5.2 on 2025-04-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('base_hp', models.IntegerField()),
                ('base_attack', models.IntegerField()),
                ('base_defense', models.IntegerField()),
                ('base_special_attack', models.IntegerField()),
                ('base_special_defense', models.IntegerField()),
                ('base_speed', models.IntegerField()),
                ('types', models.ManyToManyField(to='pokemon_app.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('capture_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=5)),
                ('iv_hp', models.IntegerField(default=0)),
                ('iv_attack', models.IntegerField(default=0)),
                ('iv_defense', models.IntegerField(default=0)),
                ('iv_special_attack', models.IntegerField(default=0)),
                ('iv_special_defense', models.IntegerField(default=0)),
                ('iv_speed', models.IntegerField(default=0)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
