# Generated by Django 5.2 on 2025-04-30 11:08

import pokemon_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemon',
            name='level',
            field=models.IntegerField(default=pokemon_app.models.random_level),
        ),
    ]
