# Generated by Django 5.2 on 2025-05-04 10:53

import django.db.models.deletion
import pokemon_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_alter_userpokemon_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemon',
            name='iv_attack',
            field=models.IntegerField(default=pokemon_app.models.random_iv),
        ),
        migrations.AlterField(
            model_name='userpokemon',
            name='iv_defense',
            field=models.IntegerField(default=pokemon_app.models.random_iv),
        ),
        migrations.AlterField(
            model_name='userpokemon',
            name='iv_hp',
            field=models.IntegerField(default=pokemon_app.models.random_iv),
        ),
        migrations.AlterField(
            model_name='userpokemon',
            name='iv_special_attack',
            field=models.IntegerField(default=pokemon_app.models.random_iv),
        ),
        migrations.AlterField(
            model_name='userpokemon',
            name='iv_special_defense',
            field=models.IntegerField(default=pokemon_app.models.random_iv),
        ),
        migrations.AlterField(
            model_name='userpokemon',
            name='iv_speed',
            field=models.IntegerField(default=pokemon_app.models.random_iv),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('selected_pokemon', models.ManyToManyField(blank=True, related_name='selected_by_profiles', to='pokemon_app.userpokemon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
