# Generated by Django 5.2 on 2025-05-07 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pokemon_app.message')),
                ('is_completed', models.BooleanField(default=False)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trades', to=settings.AUTH_USER_MODEL)),
                ('offered_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='pokemon_app.userpokemon')),
                ('traded_pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traded_for', to='pokemon_app.userpokemon')),
                ('wanted_pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to='pokemon_app.pokemon')),
            ],
            bases=('pokemon_app.message',),
        ),
    ]
